import type { IdentificationResult } from '@/src/domain/identification/types';

export const IDENTIFICATION_FIXTURE_IDS = [
  'northern-cardinal',
  'downy-woodpecker',
  'blue-jay',
  'monarch',
  'honey-bee',
  'american-bumble-bee',
  'green-anole',
  'texas-spiny-lizard',
  'bluebonnet',
  'live-oak',
  'ambiguous-swallowtail',
  'uncertain-mushroom',
  'blurry',
  'unsupported',
] as const;

export type IdentificationFixtureId = (typeof IDENTIFICATION_FIXTURE_IDS)[number];

export const IDENTIFICATION_FIXTURES: Record<IdentificationFixtureId, IdentificationResult> = {
  'northern-cardinal': {
    kind: 'highConfidence',
    taxonId: 'taxon-northern-cardinal',
    commonName: 'Northern Cardinal',
    scientificName: 'Cardinalis cardinalis',
    confidence: 0.94,
    trail: [
      { rank: 'kingdom', label: 'Animal' },
      { rank: 'class', label: 'Bird' },
      { rank: 'genus', label: 'Cardinal' },
      { rank: 'species', label: 'Northern Cardinal' },
    ],
  },
  'downy-woodpecker': {
    kind: 'highConfidence',
    taxonId: 'taxon-downy-woodpecker',
    commonName: 'Downy Woodpecker',
    scientificName: 'Dryobates pubescens',
    confidence: 0.91,
    trail: [
      { rank: 'kingdom', label: 'Animal' },
      { rank: 'class', label: 'Bird' },
      { rank: 'family', label: 'Woodpecker' },
      { rank: 'species', label: 'Downy Woodpecker' },
    ],
  },
  'blue-jay': {
    kind: 'highConfidence',
    taxonId: 'taxon-blue-jay',
    commonName: 'Blue Jay',
    scientificName: 'Cyanocitta cristata',
    confidence: 0.93,
    trail: [
      { rank: 'kingdom', label: 'Animal' },
      { rank: 'class', label: 'Bird' },
      { rank: 'genus', label: 'Jay' },
      { rank: 'species', label: 'Blue Jay' },
    ],
  },
  monarch: {
    kind: 'highConfidence',
    taxonId: 'taxon-monarch',
    commonName: 'Monarch Butterfly',
    scientificName: 'Danaus plexippus',
    confidence: 0.9,
    trail: [
      { rank: 'kingdom', label: 'Animal' },
      { rank: 'class', label: 'Insect' },
      { rank: 'family', label: 'Brush-footed butterfly' },
      { rank: 'species', label: 'Monarch Butterfly' },
    ],
  },
  'honey-bee': {
    kind: 'highConfidence',
    taxonId: 'taxon-honey-bee',
    commonName: 'Honey Bee',
    scientificName: 'Apis mellifera',
    confidence: 0.88,
    trail: [
      { rank: 'kingdom', label: 'Animal' },
      { rank: 'class', label: 'Insect' },
      { rank: 'family', label: 'Bee' },
      { rank: 'species', label: 'Honey Bee' },
    ],
  },
  'american-bumble-bee': {
    kind: 'highConfidence',
    taxonId: 'taxon-american-bumble-bee',
    commonName: 'American Bumble Bee',
    scientificName: 'Bombus pensylvanicus',
    confidence: 0.87,
    trail: [
      { rank: 'kingdom', label: 'Animal' },
      { rank: 'class', label: 'Insect' },
      { rank: 'genus', label: 'Bumble bee' },
      { rank: 'species', label: 'American Bumble Bee' },
    ],
  },
  'green-anole': {
    kind: 'highConfidence',
    taxonId: 'taxon-green-anole',
    commonName: 'Green Anole',
    scientificName: 'Anolis carolinensis',
    confidence: 0.89,
    trail: [
      { rank: 'kingdom', label: 'Animal' },
      { rank: 'class', label: 'Reptile' },
      { rank: 'family', label: 'Anole' },
      { rank: 'species', label: 'Green Anole' },
    ],
  },
  'texas-spiny-lizard': {
    kind: 'highConfidence',
    taxonId: 'taxon-texas-spiny-lizard',
    commonName: 'Texas Spiny Lizard',
    scientificName: 'Sceloporus olivaceus',
    confidence: 0.86,
    trail: [
      { rank: 'kingdom', label: 'Animal' },
      { rank: 'class', label: 'Reptile' },
      { rank: 'genus', label: 'Spiny lizard' },
      { rank: 'species', label: 'Texas Spiny Lizard' },
    ],
  },
  bluebonnet: {
    kind: 'highConfidence',
    taxonId: 'taxon-texas-bluebonnet',
    commonName: 'Texas Bluebonnet',
    scientificName: 'Lupinus texensis',
    confidence: 0.92,
    trail: [
      { rank: 'kingdom', label: 'Plant' },
      { rank: 'family', label: 'Pea' },
      { rank: 'genus', label: 'Lupine' },
      { rank: 'species', label: 'Texas Bluebonnet' },
    ],
  },
  'live-oak': {
    kind: 'highConfidence',
    taxonId: 'taxon-live-oak',
    commonName: 'Live Oak',
    scientificName: 'Quercus virginiana',
    confidence: 0.9,
    trail: [
      { rank: 'kingdom', label: 'Plant' },
      { rank: 'family', label: 'Beech' },
      { rank: 'genus', label: 'Oak' },
      { rank: 'species', label: 'Live Oak' },
    ],
  },
  'ambiguous-swallowtail': {
    kind: 'candidate',
    summaryLabel: 'This looks like a swallowtail',
    higherRank: { rank: 'family', label: 'Swallowtail' },
    candidates: [
      {
        taxonId: 'taxon-eastern-tiger-swallowtail',
        commonName: 'Eastern Tiger Swallowtail',
        scientificName: 'Papilio glaucus',
        confidence: 0.51,
        rankOrder: 1,
      },
      {
        taxonId: 'taxon-giant-swallowtail',
        commonName: 'Giant Swallowtail',
        scientificName: 'Papilio cresphontes',
        confidence: 0.37,
        rankOrder: 2,
      },
    ],
  },
  'uncertain-mushroom': {
    kind: 'higherRank',
    rank: 'kingdom',
    taxonId: null,
    commonName: 'A fungus',
    scientificName: 'Fungi',
    confidence: 0.62,
    trail: [{ rank: 'kingdom', label: 'Fungi' }],
  },
  blurry: {
    kind: 'failed',
    reason: 'The photograph is too soft to read. Try another angle.',
  },
  unsupported: {
    kind: 'unsupported',
    reason: 'Wildmark is looking for living organisms.',
  },
};
